//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEntityFrameworkBDD.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personne
    {
        public long Identifiant { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Adresse { get; set; }
        public Nullable<long> Ville { get; set; }
        public Nullable<long> Civilite { get; set; }
    
        public virtual Civilite Civilite1 { get; set; }
        public virtual Ville Ville1 { get; set; }
    }
}
